FROM python:3.11-slim

WORKDIR /app

# Copiar requirements
COPY requirements.txt .

# Instalar dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copiar dashboard
COPY Dashboard/dashboard.py .
COPY .env .

# Expor porta
EXPOSE 8050

# Rodar dashboard
CMD ["python", "dashboard.py"]